# Matrizes

In [2]:
# pip install numpy
# descomente acima se for necessário caso a biblioteca numpy não estiver instalada.

In [3]:
import numpy as np

In [4]:
matriz = np.array(
    [[2, 3, 1], [4, 5, 7]]
)  # array é como se fosse uma lista um pouco melhorada. Matriz (2x3) criada, 2 linhas e 3 colunas.

In [5]:
matriz  # interessante falar que os indicies comecam em 0.

array([[2, 3, 1],
       [4, 5, 7]])

In [6]:
matriz.shape  # shape significa formato que no caso é: (linhas, colunas)

(2, 3)

In [7]:
matriz[
    0
]  # acessanando a matriz na posição zero... retornou a primeira linha (indice zero)

array([2, 3, 1])

In [8]:
matriz[1]  # acessanando a matriz na posição um... retornou a segunda linha (indice 1)

array([4, 5, 7])

In [9]:
matriz[0][
    2
]  # para termos o retorno das colunas, precisamos de 2 colchetes. Por exemplo... o primeiro colchetes indica LINHA e o segundo colchetes indica COLUNA. Lembrem-se de trabalhar com índices.

1

In [10]:
matriz[1][2]

7

In [13]:
for i in range(matriz.shape[0]):  # shape[0] retorna o número de linhas
    print(matriz[i])
    for j in range(matriz.shape[1]):  # shape[1] retorna o número de colunas
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
