# Matrizes

In [3]:
# pip install numpy
# descomente acima se for necessário caso a biblioteca numpy não estiver instalada.


In [5]:
matriz = np.array([[2, 3, 1], [4, 5, 7]])


In [6]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [7]:
matriz.shape

(2, 3)

In [8]:
matriz[0]

array([2, 3, 1])

In [9]:
matriz[1]

array([4, 5, 7])

In [10]:
matriz[0][2]

1

In [11]:
matriz[1][2]

7

In [12]:
matriz.shape

(2, 3)

In [13]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
