# Matrizes

In [11]:
# pip install numpy
# descomente acima se for necessário caso a biblioteca numpy não estiver instalada.


In [12]:
import numpy as np  # Importa a biblioteca numpy e a renomeia como np


In [13]:
matriz = np.array(
    [[2, 3, 1], [4, 5, 7]]
)  # Cria uma matriz (array) 2x3 usando numpy, com 2 linhas e 3 colunas


In [14]:
matriz  # Exibe a matriz. Interessante notar que os índices começam em 0.


array([[2, 3, 1],
       [4, 5, 7]])

In [15]:
matriz.shape  # Retorna o formato da matriz, que no caso é: (linhas, colunas)


(2, 3)

In [16]:
matriz[
    0
]  # Acessa a matriz na posição zero, retornando a primeira linha (índice zero)


array([2, 3, 1])

In [17]:
matriz[1]  # Acessa a matriz na posição um, retornando a segunda linha (índice 1)


array([4, 5, 7])

In [18]:
matriz[0][
    2
]  # Para acessar as colunas, precisamos de 2 colchetes. O primeiro colchete indica a LINHA e o segundo colchete indica a COLUNA. Lembre-se de trabalhar com índices.


np.int64(1)

In [19]:
matriz[1][2]  # Acessa o elemento na segunda linha e terceira coluna (índices 1 e 2)


np.int64(7)

In [20]:
for i in range(matriz.shape[0]):  # Itera sobre o número de linhas da matriz
    print(matriz[i])  # Imprime a linha atual da iteração
    for j in range(matriz.shape[1]):  # Itera sobre o número de colunas da matriz
        print(matriz[i][j])  # Imprime o elemento atual da iteração

[2 3 1]
2
3
1
[4 5 7]
4
5
7
