# Fila de prioridade

In [20]:
import numpy as np

In [21]:
class FilaPrioridade:

    def __init__(self, capacidade):  # método construtor
        self.capacidade = capacidade
        self.numero_elementos = 0
        self.valores = np.empty(self.capacidade, dtype=int)

    def __fila_vazia(self):  # método auxiliar
        return self.numero_elementos == 0  # verifica se a fila esta vazia

    def __fila_cheia(self):  # método auxiliar
        return self.numero_elementos == self.capacidade  # verifica se a fila esta cheia

    def enfileirar(self, valor):
        if self.__fila_cheia():
            print("A fila está cheia")
            return

        if self.numero_elementos == 0:  # primeiro elemento
            self.valores[self.numero_elementos] = valor
            self.numero_elementos += 1  # incrementa o número de elementos na fila
        else:
            x = self.numero_elementos - 1  # posição do elemento
            while x >= 0:  # busca binária
                if valor > self.valores[x]:  # elemento é maior
                    self.valores[x + 1] = self.valores[
                        x
                    ]  # desloca para a direita o elemento para abrir espaço para o novo elemento
                else:
                    break  # sai do loop quando o elemento for menor que o valor passado como parametro
                x -= 1  # decrementa a posição do elemento
            self.valores[x + 1] = valor  # coloca o elemento na nova posição
            self.numero_elementos += 1  # incrementa o número de elementos na fila

    def desenfileirar(self):  # remover o primeiro elemento da fila
        if self.__fila_vazia():  # se a fila estiver vazia
            print("A fila está vazia")  # imprime a mensagem
            return

        valor = self.valores[
            self.numero_elementos - 1
        ]  # pega o valor do último elemento
        self.numero_elementos -= 1  # decrementa o número de elementos na fila
        return valor

    def primeiro(self):
        if self.__fila_vazia():  # se a fila estiver vazia
            return -1
        return self.valores[self.numero_elementos - 1]

In [22]:
fila = FilaPrioridade(5)

In [23]:
fila.primeiro()

-1

In [24]:
# 30
fila.enfileirar(30)
fila.primeiro()

30

In [25]:
# 50 30
fila.enfileirar(50)
fila.primeiro()

30

In [26]:
# Tradicional: 10 50 30
# Prioridade: 50 30 10
fila.enfileirar(10)
fila.primeiro()

10

In [27]:
fila.valores

array([ 50,  30,  10, 559,   0])

In [28]:
# Tradicional: 40 10 50 30
# Prioridade: 50 40 30 10
fila.enfileirar(40)
fila.primeiro()

10

In [29]:
fila.valores

array([50, 40, 30, 10,  0])

In [30]:
# Tradicional: 20 40 10 50 30
# Prioridade: 50 40 30 20 10
fila.enfileirar(20)
fila.primeiro()

10

In [31]:
fila.valores

array([50, 40, 30, 20, 10])

In [32]:
fila.enfileirar(2)

A fila está cheia


In [33]:
fila.desenfileirar()
fila.primeiro()

20

In [34]:
fila.desenfileirar()
fila.primeiro()

30

In [35]:
fila.desenfileirar()
fila.primeiro()

40

In [36]:
fila.valores

array([50, 40, 30, 20, 10])

In [37]:
fila.enfileirar(5)
fila.primeiro()

5

In [38]:
fila.valores

array([50, 40,  5, 20, 10])